## Numpy

데이터 분석을 위한 도구를 제공하는 파이썬 라이브러리. \n
다양한 배열과 행렬 연산을 처리할 수 있다

In [1]:
import numpy as np

### 차원

1. 다음 NumPy 배열의 차원 수를 출력하는 코드를 작성하세요.

In [2]:
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array.ndim

3

2. 1차원 배열 [10, 20, 30, 40, 50, 60]을 2차원 배열로 변환하여 (2, 3) 형태로 출력하는 코드를 작성하세요.

In [3]:
array = np.array([10, 20, 30, 40, 50, 60])

reshaped_vector = array.reshape(2, 3)
print("reshaped_vector:\n", reshaped_vector)
print("reshaped vector shape:", reshaped_vector.shape)

reshaped_vector:
 [[10 20 30]
 [40 50 60]]
reshaped vector shape: (2, 3)


3. 다음 1차원 배열에 새로운 차원을 추가하여 2차원 배열로 변환하고, 최종 배열의 차원 수를 출력하세요.
- `newaxis`를 사용하여 배열의 차원을 추가하고, 새로운 차원에서의 배열 모양을 확인한 후 최종 차원 수를 출력하세요.

In [4]:
array = np.array([7, 14, 21])

vector = array[:,np.newaxis]
print("vector:", vector)
print("vector shape:", vector.shape)

vector: [[ 7]
 [14]
 [21]]
vector shape: (3, 1)


### Shape

1. 주어진 2차원 NumPy 배열의 형태(Shape)를 출력하는 코드를 작성하세요.

In [5]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("array:", array)
print("array shape:", array.shape)

array: [[1 2 3]
 [4 5 6]]
array shape: (2, 3)


2. 1차원 배열 [10, 20, 30, 40, 50, 60]을 (2, 3) 형태로 변경한 후, 새로운 배열의 형태를 출력하는 코드를 작성하세요.

In [6]:
array = np.array([10, 20, 30, 40, 50, 60])
print("array:", array)
print("array shape:", array.shape)

# 배열을 2행 3열로 재구성
reshaped_array = array.reshape(2, 3)
print("reshaped_array:", reshaped_array)
print("reshaped array shape:", reshaped_array.shape)

array: [10 20 30 40 50 60]
array shape: (6,)
reshaped_array: [[10 20 30]
 [40 50 60]]
reshaped array shape: (2, 3)


3. 다음 3차원 배열의 형태를 변경하여 (3, 2, 2) 형태로 조정하고, 최종 배열의 형태를 출력하는 코드를 작성하세요.
> 🤔 원본 배열과 수정 배열 크기가 동일

In [7]:
array = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

reshaped_array = array.reshape(3, 2, 2)
print("reshaped_array:", reshaped_array)
print("reshaped array shape:", reshaped_array.shape)

reshaped_array: [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
reshaped array shape: (3, 2, 2)


### Data Type

1. 아래의 NumPy 배열의 데이터 타입을 확인하는 코드를 작성하세요.

In [8]:
array = np.array([10, 20, 30])

print("데이터 타입:", array.dtype)

데이터 타입: int64


2. 정수형 배열 [1, 2, 3]을 부동소수점형 배열로 변환하고, 변환된 배열의 데이터 타입을 출력하는 코드를 작성하세요.

In [9]:
array = np.array([1, 2, 3])

array = array.astype(np.float64)
# array = np.float64(array)
print("데이터 타입:", array.dtype)

데이터 타입: float64


> 💡 `astype(np.float64)` vs `np.float64(array)` 차이
- `astype` → 항상 `ndarray` 반환
- `np.float64()` → 스칼라 타입 생성자를 배열에 "억지로" 호출하는 것
    - `np.float64`는 원래 스칼라 값을 만들기 위한 타입으로, 요소가 1개인 배열에서 ndarray가 아닌 scalar를 돌려줘서 이후 의도하지 않은 결과가 날 수 있다.

3. NumPy 배열 [100, 200, 300]을 uint8로 변환한 후, 메모리 사용량(바이트)을 출력하는 코드를 작성하세요.

In [10]:
array = np.array([100, 200, 300])
array = array.astype(np.uint8) 

print("데이터 타입:", array.dtype)
print("메모리 사용량:", array.nbytes)

데이터 타입: uint8
메모리 사용량: 3


### Indexing

1. 주어진 1차원 배열에서 첫 번째 요소와 마지막 요소를 출력하는 코드를 작성하세요.

In [11]:
array = np.array([10, 20, 30, 40, 50])
print(array[0], array[-1])

10 50


2. 주어진 2차원 배열에서 첫 번째 열과 두 번째 행을 출력하는 코드를 작성하세요.

In [12]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix[:, 0]) # 첫 번째 열
print(matrix[1]) # 두 번째 행

[1 4 7]
[4 5 6]


3. 주어진 배열에서 10보다 큰 요소들만 선택하고, 해당 요소들의 인덱스를 출력하는 코드를 작성하세요.

In [13]:
array = np.array([5, 15, 8, 20, 3, 12])

filtered = array[array > 10]
print(filtered)
print(np.where(array > 10))

[15 20 12]
(array([1, 3, 5]),)


### Operation

1. 주어진 NumPy 배열에서 요소별(Element-wise) 덧셈을 수행하는 코드를 작성하세요.

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


2. 다음 NumPy 배열에서 브로드캐스팅을 활용하여 각 행에 [1, 2, 3]을 더하는 코드를 작성하세요.

In [15]:
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])

result = matrix + vector
print(result)

[[11 22 33]
 [41 52 63]]


3. 주어진 2차원 NumPy 배열에 대해, 축(axis)을 기준으로 최댓값을 구하고 최종 배열의 차원을 출력하는 코드를 작성하세요.

In [16]:
array = np.array([[3, 7, 2], [8, 4, 6]])

array_t = array.transpose()
print(array_t)
print([max(i) for i in array_t])
print(array_t.shape)

# print(np.linalg.inv(array))

[[3 8]
 [7 4]
 [2 6]]
[np.int64(8), np.int64(7), np.int64(6)]
(3, 2)


### Universal Function

1. 배열 [1, 2, 3, 4]에 대해 NumPy의 유니버설 함수를 사용하여 모든 요소를 제곱한 결과를 출력하는 코드를 작성하세요. 

In [17]:
array = np.array([1, 2, 3, 4])
answer = np.power(array, 2)
print(answer)

[ 1  4  9 16]


2. 다음 두 배열의 요소별 합을 계산하고, 결과를 새로운 배열이 아닌 기존 배열에 저장하는 코드를 작성하세요.

In [18]:
array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])
result = np.empty_like(array2)  

np.add(array1, array2, out = result)
print(result)

[11 22 33]


3. 다음 배열에 대해 NumPy 유니버설 함수를 사용하여 요소별로 자연로그(log)를 계산하고, 특정 조건(log 값 > 1)을 만족하는 요소만 출력하는 코드를 작성하세요.

In [19]:
array = np.array([1, np.e, 10, 100])
log_array = np.log(array)
result = log_array[log_array > 1]
print(result)

[2.30258509 4.60517019]
